#include "Periph/Shaders.h"

char vShaderStr[] =
   "#version 300 es                            \n"
   "layout(location = 0) in vec4 a_position;   \n"
   "layout(location = 1) in vec2 a_texCoord;   \n"
   "out vec2 v_texCoord;                       \n"
   "void main()                                \n"
   "{                                          \n"
   "   gl_Position = a_position;               \n"
   "   v_texCoord = a_texCoord;                \n"
   "}                                          \n";

char fShaderStrGrayscale[] =
   "#version 300 es                                     \n"
   "precision mediump float;                            \n"
   "in vec2 v_texCoord;                                 \n"
   "layout(location = 0) out vec4 outColor;             \n"
   "uniform sampler2D s_baseNew;                        \n"
   "void main()                                         \n"
   "{                                                   \n"
   "  float grayscaleColor;                                                  \n"
   "  vec4 baseColor;                                                        \n"
   "  baseColor = texture( s_baseNew, v_texCoord );                         \n"
   "  grayscaleColor = (baseColor.r+baseColor.g+baseColor.b)*0.3;             \n"
   "  outColor = vec4(grayscaleColor,grayscaleColor,grayscaleColor,1.0);    \n"
   "}    \n";

char fShaderStr[] =
   "#version 300 es                                     \n"
   "precision mediump float;                            \n"
   "in vec2 v_texCoord;                                 \n"
   "layout(location = 0) out vec4 outColor;             \n"
   "uniform sampler2D s_baseNew;                        \n"
   "uniform float grayscale;                           \n"
   "uniform float brightness;                           \n"
   "void main()                                         \n"
   "{                                                   \n"
   "  float grayscaleColor;                                                  \n"
   "  vec4 baseColor;                                   \n"
   "  baseColor = texture( s_baseNew, v_texCoord );      \n"
   "  if(grayscale>0.0)                                       \n"
   "  {                                                                 \n"
   "    grayscaleColor = (baseColor.r+baseColor.g+baseColor.b)*0.3;             \n"
   "    outColor = vec4(grayscaleColor*brightness*1.2f,grayscaleColor*brightness*1.2f,grayscaleColor*brightness*1.2f,1.0);    \n"
   "  }                                                  \n"
   "  else                                               \n"
   "  {                                                      "
   "    outColor = vec4(baseColor.r*brightness*1.2f,baseColor.g*brightness*1.2f,baseColor.b*brightness*1.2f,1.0);  \n"
   "  } \n"
   "}    \n";

char fShaderCrosshair[] =
  "#version 300 es                                     \n"
  "precision mediump float;                            \n"
  "in vec2 v_texCoord;                                 \n"
  "layout(location = 0) out vec4 outColor;             \n"
  "uniform sampler2D s_baseMap;                        \n"
  "uniform vec4 color;                           \n"
  "void main()                                         \n"
  "{                                                   \n"
  "  vec4 baseColor;                                   \n"
  "  float alphaValue;                                   \n"
  "                                                    \n"
  "  baseColor = texture( s_baseMap, v_texCoord );          \n"
  "  alphaValue = (baseColor.r+baseColor.g+baseColor.b)*0.3; \n"
  "  if(alphaValue<0.3f)                                \n"
  "  {                                                  \n"
  "      discard;                                       \n"
  "  }                                                  \n"
  "  else                                               \n"
  "  {                                                   \n"
  "     outColor = vec4(color.r*alphaValue,color.g*alphaValue,color.b*alphaValue,color.a);  \n"
  "     \n"
  "  }  \n"
  "} \n";

char fShaderCompassScale[] =
  "#version 300 es                                     \n"
  "precision mediump float;                            \n"
  "in vec2 v_texCoord;                                 \n"
  "layout(location = 0) out vec4 outColor;             \n"
  "uniform sampler2D s_baseMap;                        \n"
  "uniform vec4 backgroundColor;                                  \n"
  "void main()                                         \n"
  "{                                                   \n"
  "  vec4 baseColor;                                   \n"
  "  float alphaValue;                                   \n"
  "                                                    \n"
  "  baseColor = texture( s_baseMap, v_texCoord );          \n"
  "  alphaValue = (baseColor.r+baseColor.g+baseColor.b)*0.3; \n"
  "  if(alphaValue<0.3f)                                \n"
  "  {                                                  \n"
  "      outColor = backgroundColor;                    \n"
  "  }                                                  \n"
  "  else                                               \n"
  "  {                                                  \n"
  "      outColor = vec4(baseColor.b,baseColor.g,baseColor.r,1.0);                          \n"
  "  }                                                  \n"
  "} \n";

char fShaderHighlightedText[] =
  "#version 300 es                                     \n"
  "precision mediump float;                            \n"
  "in vec2 v_texCoord;                                 \n"
  "layout(location = 0) out vec4 outColor;             \n"
  "uniform sampler2D s_baseMap;                        \n"
  "uniform vec4 backgroundColor;                       \n"
  "uniform vec4 fillColor;                              \n"
  "void main()                                         \n"
  "{                                                   \n"
  "  vec4 baseColor;                                   \n"
  "  float alphaValue;                                   \n"
  "                                                    \n"
  "  baseColor = texture( s_baseMap, v_texCoord );          \n"
  "  alphaValue = (baseColor.r+baseColor.g+baseColor.b)*0.3; \n"
  "  if(alphaValue<0.3f)                                \n"
  "  {                                                  \n"
  "      outColor = backgroundColor;                    \n"
  "  }                                                  \n"
  "  else                                               \n"
  "  {                                                  \n"
  "      outColor = fillColor;                          \n"
  "  }                                                  \n"
  "} \n";

char fShaderTiltScale[] =
  "#version 300 es                                     \n"
  "precision mediump float;                            \n"
  "in vec2 v_texCoord;                                 \n"
  "layout(location = 0) out vec4 outColor;             \n"
  "uniform sampler2D s_baseMap;                        \n"
  "uniform sampler2D s_mask;                        \n"
  "uniform vec4 backgroundColor;                       \n"
  "uniform float offsetY;                               \n"
  "void main()                                         \n"
  "{    "
  "  vec4 maskColor;                                               \n"
  "  vec4 baseColor;                                   \n"
  "  float alphaValue; "
  "  vec2 vTxtCoord;"
  "  vTxtCoord.x =  v_texCoord.x;                         \n"
  "  vTxtCoord.y =  v_texCoord.y+offsetY;                         \n"
  "                                                    \n"
  "  maskColor = texture( s_mask, v_texCoord );                             \n"
  "  baseColor = texture( s_baseMap, vTxtCoord );                           \n"
  "  alphaValue = ((baseColor.r+baseColor.g+baseColor.b)*0.3); \n"
  "  if(alphaValue<0.3f)                                                    \n"
  "  {                                                  \n"
  "      outColor = backgroundColor;                    \n"
  "  }                                                  \n"
  "  else                                               \n"
  "  {                                                  \n"
  "      outColor = vec4(baseColor.b,baseColor.g,baseColor.r,1.0);                          \n"
  "  }                                                  "
  "      outColor.a=outColor.a*maskColor.r;                                            \n"
  "} \n";

char fShaderCompassPointer[] =
  "#version 300 es                                     \n"
  "precision mediump float;                            \n"
  "in vec2 v_texCoord;                                 \n"
  "layout(location = 0) out vec4 outColor;             \n"
  "uniform sampler2D s_baseMap;                        \n"
  "void main()                                         \n"
  "{                                                   \n"
  "  vec4 baseColor;                                   \n"
  "  float alphaValue;                                   \n"
  "                                                    \n"
  "  baseColor = texture( s_baseMap, v_texCoord );          \n"
  "  alphaValue = (baseColor.r+baseColor.g+baseColor.b)*0.3; \n"
  "  if(alphaValue<0.01f)                                \n"
  "  {                                                  \n"
  "      discard;                    \n"
  "  }                                                  \n"
  "  else                                               \n"
  "  {                                                  \n"
  "   outColor = vec4(baseColor.b,baseColor.g,baseColor.r,1.0);                             \n"
  "  }                                                  \n"
  "} \n";

char fShaderBattery[] =
  "#version 300 es                                     \n"
  "precision mediump float;                            \n"
  "in vec2 v_texCoord;                                 \n"
  "layout(location = 0) out vec4 outColor;             \n"
  "uniform sampler2D s_baseMap;                        \n"
  "uniform vec4 backgroundColor;                                  \n"
  "uniform float batteryPercentage;                        \n"
  "void main()                                         \n"
  "{                                                   \n"
  "  vec4 baseColor;                                   \n"
  "  float alphaValue;                                   \n"
  "  baseColor = texture( s_baseMap, v_texCoord );          \n"
  "  alphaValue = (baseColor.r+baseColor.g+baseColor.b)*0.3; \n"
  "  if(alphaValue<0.1f)                                \n"
  "  {                                                  \n"
  "      outColor = vec4(0.0,0.0,0.0,0.0);                                       \n"
  "  }                                                  \n"
  "  else                                               \n"
  "  {                                                  \n"
  "     if(baseColor.r>0.0f)                                            \n"
  "      {                                                              \n"
  "         outColor = vec4(baseColor.b,baseColor.g,baseColor.r,1.0);                 \n"
  "      }                                                              \n"
  "      else                                                           \n"
  "      {                                                              \n"
  "         if(baseColor.b>0.0f)                                        \n"
  "         {                                                           \n"
      "         if(baseColor.g<batteryPercentage)                           \n"
      "         {                                                           \n"
      "             outColor = vec4((1.0f-batteryPercentage)*2.0f,batteryPercentage*2.0f,0.0,1.0);                       \n"
      "         }                                                           \n"
      "         else                                                         \n"
      "         {                                                            \n"
      "             outColor = vec4(0.0,0.0,0.0,0.0);                                            \n"
      "         }                                               \n"
  "         }                                                     \n"
  "         else                                                         \n"
  "         {                                                            \n"
  "             outColor = vec4(0.0,0.0,0.0,0.0);                                            \n"
  "         }                                                     \n"
  "      }                                                          \n"
  "  }                                                  \n"
  "} \n";
